<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SampahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            [
                'id' => 437,
                'kategori' => 'Daur Ulang',
                'jumlah' => 61,
                'tanggal' => '2023-11-30',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 438,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 51,
                'tanggal' => '2023-11-30',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 439,
                'kategori' => 'Organik',
                'jumlah' => 80,
                'tanggal' => '2024-11-11',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 440,
                'kategori' => 'Anorganik',
                'jumlah' => 60,
                'tanggal' => '2024-11-11',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 441,
                'kategori' => 'Daur Ulang',
                'jumlah' => 45,
                'tanggal' => '2024-11-11',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 442,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 30,
                'tanggal' => '2024-11-11',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 443,
                'kategori' => 'Organik',
                'jumlah' => 82,
                'tanggal' => '2024-11-12',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 444,
                'kategori' => 'Anorganik',
                'jumlah' => 62,
                'tanggal' => '2024-11-12',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 445,
                'kategori' => 'Daur Ulang',
                'jumlah' => 48,
                'tanggal' => '2024-11-12',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 446,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 32,
                'tanggal' => '2024-11-12',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 447,
                'kategori' => 'Organik',
                'jumlah' => 85,
                'tanggal' => '2024-11-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 448,
                'kategori' => 'Anorganik',
                'jumlah' => 64,
                'tanggal' => '2024-11-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 449,
                'kategori' => 'Daur Ulang',
                'jumlah' => 50,
                'tanggal' => '2024-11-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 450,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 34,
                'tanggal' => '2024-11-13',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 451,
                'kategori' => 'Organik',
                'jumlah' => 88,
                'tanggal' => '2024-11-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 452,
                'kategori' => 'Anorganik',
                'jumlah' => 66,
                'tanggal' => '2024-11-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 453,
                'kategori' => 'Daur Ulang',
                'jumlah' => 52,
                'tanggal' => '2024-11-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 454,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 35,
                'tanggal' => '2024-11-14',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 455,
                'kategori' => 'Organik',
                'jumlah' => 90,
                'tanggal' => '2024-11-15',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 456,
                'kategori' => 'Anorganik',
                'jumlah' => 68,
                'tanggal' => '2024-11-15',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 457,
                'kategori' => 'Daur Ulang',
                'jumlah' => 55,
                'tanggal' => '2024-11-15',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 458,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 37,
                'tanggal' => '2024-11-15',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 459,
                'kategori' => 'Organik',
                'jumlah' => 92,
                'tanggal' => '2024-11-16',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 460,
                'kategori' => 'Anorganik',
                'jumlah' => 70,
                'tanggal' => '2024-11-16',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 461,
                'kategori' => 'Daur Ulang',
                'jumlah' => 57,
                'tanggal' => '2024-11-16',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 462,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 39,
                'tanggal' => '2024-11-16',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 463,
                'kategori' => 'Organik',
                'jumlah' => 95,
                'tanggal' => '2024-11-17',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 464,
                'kategori' => 'Anorganik',
                'jumlah' => 72,
                'tanggal' => '2024-11-17',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 465,
                'kategori' => 'Daur Ulang',
                'jumlah' => 60,
                'tanggal' => '2024-11-17',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 466,
                'kategori' => 'Tidak Bisa Daur Ulang',
                'jumlah' => 40,
                'tanggal' => '2024-11-17',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        DB::table('sampah')->insert($data);
    }
}
